import { Language, ProjectFilter } from './portfolio-data';

export const languages: { code: Language; label: string }[] = [
  { code: 'en', label: 'EN' },
  { code: 'es', label: 'ES' },
  { code: 'pt', label: 'PT' },
];

export const projectFilters: ProjectFilter[] = [
  'all',
  'industrial',
  'enterprise',
  'logistics',
  'ai',
  'product',
];

export const stack = [
  'C#',
  '.NET Framework',
  '.NET Core',
  '.NET 8',
  'ASP.NET MVC',
  'ASP.NET Core',
  'ASP.NET Web API',
  'ASP.NET WebForms',
  'Entity Framework',
  'Entity Framework Core',
  'LINQ',
  'Hangfire',
  'Node.js',
  'NestJS',
  'REST APIs',
  'SignalR',
  'Angular',
  'React',
  'Next.js',
  'React Native',
  'Expo',
  'TypeScript',
  'JavaScript',
  'HTML5',
  'CSS3',
  'SCSS',
  'Tailwind CSS',
  'PrimeNG',
  'DevExtreme',
  'ShadCN UI',
  'RxJS',
  'SQL Server',
  'Oracle Database',
  'PostgreSQL',
  'MongoDB',
  'MongoDB Atlas',
  'Redis',
  'TimescaleDB',
  'Azure',
  'AWS',
  'Azure App Services',
  'Azure Functions',
  'Azure SQL',
  'Azure DevOps',
  'Azure Pipelines',
  'Azure Key Vault',
  'Azure AD',
  'Application Insights',
  'AWS EC2',
  'AWS Lambda',
  'AWS API Gateway',
  'AWS EventBridge',
  'AWS CloudWatch',
  'AWS RDS',
  'AWS IAM',
  'AWS ECS',
  'AWS S3',
  'Docker',
  'Docker Compose',
  'Nginx',
  'GitHub Actions',
  'CI/CD',
  'Linux',
  'Container Registries',
  'MSAL',
  'JWT',
  'OAuth2',
  'OpenID Connect',
  '2FA',
  'Authentication',
  'Authorization',
  'CQRS',
  'Microservices',
  'Microfrontends',
  'Backend For Frontend',
  'Clean Architecture',
  'DDD',
  'Event-Driven Architecture',
  'Separation of Concerns',
  'Multi-Tenant Applications',
  'Serverless',
  'MQTT',
  'WebRTC',
  'Datadog',
  'Serilog',
  'SonarQube',
  'Snyk',
];

const rowBreak = Math.ceil(stack.length / 2);
export const marqueeRows = [stack.slice(0, rowBreak), stack.slice(rowBreak)];

export const contactLinks = [
  { label: 'GitHub', href: 'https://www.github.com/romulo-ribeiro' },
  { label: 'LinkedIn', href: 'https://www.linkedin.com/in/romulobribeiro' },
];
